[font]
# Normal font style
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style (Inherits family from normal)
bold = { style = "Bold" }  #  Default style: Bold

# Italic font style (Inherits family from normal)
#italic = { style = "Oblique" }  # Default style: Italic

# Bold Italic font style (Inherits family from normal)
#bold_italic = { style = "Bold Oblique" }  # Default style: Bold Italic

# Font size in points
size = 13  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 1 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true
