[general]
import = [
  # uncomment the flavour you want below:
  # "themes/catppuccin/catppuccin-latte.toml",
  "~/.config/alacritty/themes/rigel.toml",
  "fonts/default.toml",
]
# Working directory
working_directory = "None"  # Default: "None"

# Live config reload (changes require restart)
live_config_reload = true  # Default: true

# Offer IPC using alacritty msg (unix only)
ipc_socket = true  # Default: true


[env]
TERM = "xterm-256color"
# Example
WINIT_X11_SCALE_FACTOR = "1.0"

# The path of your favorite shell
[terminal]
shell.program = "/bin/zsh"
shell.args = ["-l"]
#, "-c", "zellij attach --index 0 --create"] # connect to zellij session0 or create new session


[window]
# Blank space added around the window in pixels
padding = { x = 3, y = 3 }
# Spread additional padding evenly around the terminal content
dynamic_padding = true
# 透明率
opacity = 0.7
# Make Option key behave as Alt.
option_as_alt = "None"  # Default: "None"


[colors]
#specify in themes


[font]

# Normal font style
#normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
#bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
#italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
#bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 15  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
#glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
#builtin_box_drawing = true  # Default: true


# ====================== HINTS ======================
[hints]

# Define the keys used for hint labels
alphabet = "jfkdls;ahgurieowpq"  # Default: "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


# ====================== KEYBOARD ======================
[keyboard]
# Example
bindings = [
     { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
     { key = "Back", mods = "Command", chars ="\u0015"}, # all del left to cursur
]


# ====================== DEBUG ======================
[debug]

# Display the time it takes to draw each frame.
render_timer = false # Default: false

# Keep the log file after quitting Alacritty.
persistent_logging = false # Default: false

log_level = "Warn" # Default: "Warn"

# Force use of a specific renderer, "None" will use the highest available one.
renderer = "None" # Default: "None" 

# Log all received window events.
print_events = false # Default: false

# Highlight window damage information.
highlight_damage = false # Default: false

# Use EGL as display API if the current platform allows it.
prefer_egl = false # Default: false
